default:
  image: node:14

stages:
  - test
  - tag
  # - deploy

run-tests:
  stage: test
  except:
    - tags
  services:
    - name: 'docker.elastic.co/elasticsearch/elasticsearch:7.12.0'
      alias: 'elasticsearch'
      command: ['bin/elasticsearch', '-Expack.security.enabled=false', '-Ediscovery.type=single-node']
    - name: 'opensearchproject/opensearch:1.2.4'
      alias: 'opensearch'
      command: ['bin/opensearch', '-Eplugins.security.disabled=true', '-Ediscovery.type=single-node']
  script:
    - yarn
    - yarn lint
    - yarn build
    - SEARCH_ENDPOINT='http://opensearch:9200' yarn test && SEARCH_ENDPOINT='http://elasticsearch:9200' yarn test

tag:
  stage: tag
  only:
    - master
  script:
    - npx semantic-release
# deploy:
#   stage: deploy
#   only:
#     - tags
#   environment:
#     name: npm
#     url: https://www.npmjs.com/package/@scalenc/opensearch-mapping-ts
#   script:
#     - 'sed -ie "s/\"version\":[ ]*\"[^\"]*\"/\"version\": \"`git describe --tags | tr -d v`\"/g" package.json'
#     - yarn global add serverless@2.34 --no-progress
#     - yarn
#     - yarn run deploy --stage dev --verbose

